// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ping {
    #[prost(int32, tag = "1")]
    pub nonce: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Register {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub proxy: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub module: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub addons: ::prost::alloc::vec::Vec<Addon>,
    #[prost(message, optional, tag = "5")]
    pub timer: ::core::option::Option<Timer>,
    #[prost(message, optional, tag = "11")]
    pub sysinfo: ::core::option::Option<SysInfo>,
    /// implant的公钥，用于server加密数据
    #[prost(message, optional, tag = "12")]
    pub secure: ::core::option::Option<Secure>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Secure {
    #[prost(bool, tag = "1")]
    pub enable: bool,
    /// encryption key
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    /// encryption type
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    /// implant的公钥，用于server加密数据
    #[prost(string, tag = "4")]
    pub public_key: ::prost::alloc::string::String,
}
/// Age 密钥交换相关消息
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyExchangeRequest {
    /// 临时公钥 (Age X25519)
    #[prost(string, tag = "1")]
    pub public_key: ::prost::alloc::string::String,
    /// 对临时公钥的签名
    #[prost(bytes = "vec", tag = "2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// 时间戳
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
    /// 随机数
    #[prost(string, tag = "4")]
    pub nonce: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyExchangeResponse {
    /// Server 临时公钥
    #[prost(string, tag = "1")]
    pub public_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Init {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SysInfo {
    #[prost(string, tag = "1")]
    pub filepath: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub workdir: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_privilege: bool,
    #[prost(message, optional, tag = "11")]
    pub os: ::core::option::Option<Os>,
    #[prost(message, optional, tag = "12")]
    pub process: ::core::option::Option<Process>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Suicide {
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
}
/// common empty request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub input: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "4")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bytes = "vec", tag = "5")]
    pub bin: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(string, tag = "1")]
    pub output: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub kv: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, repeated, tag = "4")]
    pub array: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BypassRequest {
    #[prost(bool, tag = "1")]
    pub etw: bool,
    #[prost(bool, tag = "2")]
    pub amsi: bool,
    #[prost(bool, tag = "3")]
    pub block_dll: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetInterface {
    #[prost(int32, tag = "1")]
    pub index: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mac: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub ip_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SockTabEntry {
    #[prost(string, tag = "1")]
    pub local_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub remote_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sk_state: ::prost::alloc::string::String,
    ///   uint32 uid = 4;
    #[prost(string, tag = "5")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub protocol: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetstatResponse {
    #[prost(message, repeated, tag = "1")]
    pub socks: ::prost::alloc::vec::Vec<SockTabEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Block {
    #[prost(uint32, tag = "1")]
    pub block_id: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub end: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(bool, tag = "3")]
    pub end: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Os {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// kernel version
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// release version
    #[prost(string, tag = "3")]
    pub release: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub arch: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub hostname: ::prost::alloc::string::String,
    /// timezone
    #[prost(string, tag = "7")]
    pub locale: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "8")]
    pub clr_version: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Process {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub pid: u32,
    #[prost(uint32, tag = "3")]
    pub ppid: u32,
    #[prost(string, tag = "4")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub arch: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub args: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub uid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Timer {
    #[prost(string, tag = "1")]
    pub expression: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub jitter: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_dir: bool,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(int64, tag = "4")]
    pub mod_time: i64,
    #[prost(uint32, tag = "5")]
    pub mode: u32,
    #[prost(string, tag = "6")]
    pub link: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SacrificeProcess {
    #[prost(bool, tag = "1")]
    pub hidden: bool,
    #[prost(bool, tag = "2")]
    pub block_dll: bool,
    #[prost(bool, tag = "3")]
    pub etw: bool,
    #[prost(uint32, tag = "4")]
    pub ppid: u32,
    #[prost(string, tag = "5")]
    pub argue: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LsResponse {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub exists: bool,
    #[prost(message, repeated, tag = "3")]
    pub files: ::prost::alloc::vec::Vec<FileInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DriveInfo {
    /// "C:\\"
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// "Fixed drive"
    #[prost(string, tag = "2")]
    pub drive_type: ::prost::alloc::string::String,
    ///
    #[prost(uint64, tag = "3")]
    pub total_size: u64,
    ///
    #[prost(uint64, tag = "4")]
    pub free_size: u64,
    /// "NTFS"
    #[prost(string, tag = "5")]
    pub file_system: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumDriversResponse {
    #[prost(message, repeated, tag = "1")]
    pub drives: ::prost::alloc::vec::Vec<DriveInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PsResponse {
    #[prost(message, repeated, tag = "1")]
    pub processes: ::prost::alloc::vec::Vec<Process>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "3")]
    pub output: bool,
    #[prost(bool, tag = "4")]
    pub singleton: bool,
    #[prost(bool, tag = "5")]
    pub realtime: bool,
    #[prost(uint32, tag = "10")]
    pub ppid: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecResponse {
    #[prost(int32, tag = "1")]
    pub status_code: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub stdout: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub stderr: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "4")]
    pub pid: u32,
    #[prost(bool, tag = "5")]
    pub end: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BinaryResponse {
    /// common return, bof BeaconOutput
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// bof BeaconPrintf
    #[prost(bytes = "vec", tag = "2")]
    pub message: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub err: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Modules {
    #[prost(string, repeated, tag = "1")]
    pub modules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Addons {
    #[prost(message, repeated, tag = "1")]
    pub addons: ::prost::alloc::vec::Vec<Addon>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Addon {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub depend: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoadModule {
    #[prost(string, tag = "1")]
    pub bundle: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub bin: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoadAddon {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub depend: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub bin: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteAddon {
    #[prost(string, tag = "1")]
    pub addon: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub execute_binary: ::core::option::Option<ExecuteBinary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteBinary {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub bin: ::prost::alloc::vec::Vec<u8>,
    #[prost(map = "string, string", tag = "3")]
    pub param: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "4")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub process_name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "7")]
    pub entry_point: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "8")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "9")]
    pub output: bool,
    #[prost(uint32, tag = "10")]
    pub arch: u32,
    #[prost(uint32, tag = "11")]
    pub timeout: u32,
    #[prost(message, optional, tag = "12")]
    pub sacrifice: ::core::option::Option<SacrificeProcess>,
    #[prost(string, tag = "13")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub context: ::prost::alloc::string::String,
    /// millisecond
    #[prost(uint32, tag = "15")]
    pub delay: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteCommand {
    #[prost(string, tag = "1")]
    pub command: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub sacrifice: ::core::option::Option<SacrificeProcess>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub r#priv: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "5")]
    pub hidden: bool,
    #[prost(bool, tag = "6")]
    pub r#override: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DownloadRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub buffer_size: u32,
    #[prost(bool, tag = "4")]
    pub dir: bool,
    #[prost(int32, tag = "5")]
    pub cur: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DownloadResponse {
    #[prost(string, tag = "1")]
    pub checksum: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub size: u64,
    #[prost(int32, tag = "3")]
    pub cur: i32,
    #[prost(bytes = "vec", tag = "4")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CurlRequest {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub timeout: i32,
    #[prost(string, tag = "3")]
    pub method: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    #[prost(map = "string, string", tag = "5")]
    pub header: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "6")]
    pub hostname: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChownRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub uid: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub gid: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub recursive: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IfconfigResponse {
    #[prost(message, repeated, tag = "1")]
    pub net_interfaces: ::prost::alloc::vec::Vec<NetInterface>,
}
/// wrap for client
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegistryRequest {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub registry: ::core::option::Option<Registry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Registry {
    #[prost(string, tag = "1")]
    pub hive: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegistryWriteRequest {
    #[prost(string, tag = "1")]
    pub hive: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub string_value: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub byte_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "7")]
    pub dword_value: u32,
    #[prost(uint64, tag = "8")]
    pub qword_value: u64,
    #[prost(uint32, tag = "10")]
    pub regtype: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TaskScheduleRequest {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub taskschd: ::core::option::Option<TaskSchedule>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TaskSchedule {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub executable_path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub trigger_type: u32,
    #[prost(string, tag = "5")]
    pub start_boundary: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub description: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub enabled: bool,
    #[prost(string, tag = "8")]
    pub last_run_time: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub next_run_time: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskSchedulesResponse {
    #[prost(message, repeated, tag = "1")]
    pub schedules: ::prost::alloc::vec::Vec<TaskSchedule>,
}
/// wrap for client
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServiceRequest {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub service: ::core::option::Option<ServiceConfig>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServiceConfig {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub executable_path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub start_type: u32,
    #[prost(uint32, tag = "5")]
    pub error_control: u32,
    #[prost(string, tag = "6")]
    pub account_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServiceStatus {
    #[prost(uint32, tag = "1")]
    pub current_state: u32,
    #[prost(uint32, tag = "2")]
    pub process_id: u32,
    #[prost(uint32, tag = "3")]
    pub exit_code: u32,
    #[prost(uint32, tag = "4")]
    pub checkpoint: u32,
    #[prost(uint32, tag = "5")]
    pub wait_hint: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Service {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<ServiceConfig>,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<ServiceStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServicesResponse {
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<Service>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WmiQueryRequest {
    #[prost(string, tag = "1")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WmiMethodRequest {
    #[prost(string, tag = "1")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub method_name: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RunAsRequest {
    /// 需要执行的用户名
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// 用户所属域
    #[prost(string, tag = "2")]
    pub domain: ::prost::alloc::string::String,
    /// 用户密码
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    /// 程序路径
    #[prost(string, tag = "4")]
    pub program: ::prost::alloc::string::String,
    /// 程序参数（可选）
    #[prost(string, tag = "5")]
    pub args: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub use_profile: bool,
    /// 是否仅使用网络凭据 (可选，默认 false)
    #[prost(bool, tag = "7")]
    pub netonly: bool,
    #[prost(bool, tag = "8")]
    pub use_env: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSystem {
    #[prost(bytes = "vec", tag = "1")]
    pub bin: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub pid: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Inject {
    #[prost(bytes = "vec", tag = "1")]
    pub bin: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub pid: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pipe {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PipeRequest {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub pipe: ::core::option::Option<Pipe>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Switch {
    #[prost(string, repeated, tag = "1")]
    pub urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TaskCtrl {
    #[prost(uint32, tag = "1")]
    pub task_id: u32,
    #[prost(string, tag = "2")]
    pub op: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TaskInfo {
    #[prost(uint32, tag = "1")]
    pub task_id: u32,
    #[prost(uint64, tag = "2")]
    pub last: u64,
    #[prost(uint32, tag = "3")]
    pub recv_count: u32,
    #[prost(uint32, tag = "4")]
    pub send_count: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskListResponse {
    #[prost(message, repeated, tag = "1")]
    pub tasks: ::prost::alloc::vec::Vec<TaskInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FFmpegRequest {
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub output_format: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub output_path: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub time: ::prost::alloc::string::String,
}
/// PTY
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PtyRequest {
    /// type: "start", "input", "stop"
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    ///
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    /// shell type: "/bin/bash", "cmd.exe", "powershell.exe"
    #[prost(string, tag = "3")]
    pub shell: ::prost::alloc::string::String,
    ///
    #[prost(uint32, tag = "4")]
    pub cols: u32,
    ///
    #[prost(uint32, tag = "5")]
    pub rows: u32,
    ///
    #[prost(bytes = "vec", tag = "6")]
    pub input_data: ::prost::alloc::vec::Vec<u8>,
    ///
    #[prost(string, tag = "7")]
    pub input_text: ::prost::alloc::string::String,
    ///
    #[prost(map = "string, string", tag = "8")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PtyResponse {
    /// 会话ID
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// 输出数据（二进制）
    #[prost(bytes = "vec", tag = "2")]
    pub output_data: ::prost::alloc::vec::Vec<u8>,
    /// 输出数据（文本）
    #[prost(string, tag = "3")]
    pub output_text: ::prost::alloc::string::String,
    /// 错误信息
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    /// 会话是否仍然活跃
    #[prost(bool, tag = "5")]
    pub session_active: bool,
    #[prost(string, repeated, tag = "6")]
    pub active_sessions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "7")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
