## windows
[target.x86_64-pc-windows-msvc]
image = "ghcr.io/chainreactors/x86_64-pc-windows-msvc-cross:latest"

[target.i686-pc-windows-msvc]
image = "ghcr.io/chainreactors/i686-pc-windows-msvc-cross:latest"

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/chainreactors/x86_64-pc-windows-gnu:latest"

[target.i686-pc-windows-gnu]
image = "ghcr.io/chainreactors/i686-pc-windows-gnu:latest"

## mac
[target.x86_64-apple-darwin]
image = "ghcr.io/chainreactors/x86_64-apple-darwin-cross:latest"

[target.aarch64-apple-darwin]
image = "ghcr.io/chainreactors/aarch64-apple-darwin-cross:latest"

## linux
[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/chainreactors/x86_64-unknown-linux-gnu:latest"

[target.i686-unknown-linux-gnu]
image = "ghcr.io/chainreactors/i686-unknown-linux-gnu:latest"