[toolchain]
channel = "nightly-2024-08-16"
targets = [
    "x86_64-pc-windows-gnu",
    "i686-pc-windows-gnu",
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]