/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "module.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: malefic_LsResponse, malefic_PsResponse, malefic_TaskSchedulesResponse, malefic_ServicesResponse, malefic_CommonBody */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: malefic_LsResponse, malefic_PsResponse, malefic_TaskSchedulesResponse, malefic_ServicesResponse, malefic_CommonBody
#endif
PB_BIND(malefic_Ping, malefic_Ping, AUTO)


PB_BIND(malefic_Register, malefic_Register, 4)


PB_BIND(malefic_Secure, malefic_Secure, 2)


PB_BIND(malefic_KeyExchangeRequest, malefic_KeyExchangeRequest, 2)


PB_BIND(malefic_KeyExchangeResponse, malefic_KeyExchangeResponse, 2)


PB_BIND(malefic_Init, malefic_Init, 4)


PB_BIND(malefic_SysInfo, malefic_SysInfo, 2)


PB_BIND(malefic_Suicide, malefic_Suicide, AUTO)


PB_BIND(malefic_Request, malefic_Request, 4)


PB_BIND(malefic_Request_ParamsEntry, malefic_Request_ParamsEntry, AUTO)


PB_BIND(malefic_Response, malefic_Response, 4)


PB_BIND(malefic_Response_KvEntry, malefic_Response_KvEntry, AUTO)


PB_BIND(malefic_BypassRequest, malefic_BypassRequest, AUTO)


PB_BIND(malefic_NetInterface, malefic_NetInterface, 2)


PB_BIND(malefic_SockTabEntry, malefic_SockTabEntry, AUTO)


PB_BIND(malefic_NetstatResponse, malefic_NetstatResponse, 4)


PB_BIND(malefic_Block, malefic_Block, 4)


PB_BIND(malefic_ACK, malefic_ACK, AUTO)


PB_BIND(malefic_Os, malefic_Os, 2)


PB_BIND(malefic_Process, malefic_Process, 2)


PB_BIND(malefic_Timer, malefic_Timer, AUTO)


PB_BIND(malefic_FileInfo, malefic_FileInfo, 2)


PB_BIND(malefic_SacrificeProcess, malefic_SacrificeProcess, 2)


PB_BIND(malefic_LsResponse, malefic_LsResponse, 4)


PB_BIND(malefic_DriveInfo, malefic_DriveInfo, AUTO)


PB_BIND(malefic_EnumDriversResponse, malefic_EnumDriversResponse, 2)


PB_BIND(malefic_PsResponse, malefic_PsResponse, 4)


PB_BIND(malefic_ExecRequest, malefic_ExecRequest, 4)


PB_BIND(malefic_ExecResponse, malefic_ExecResponse, 4)


PB_BIND(malefic_BinaryResponse, malefic_BinaryResponse, 4)


PB_BIND(malefic_Modules, malefic_Modules, 4)


PB_BIND(malefic_Addons, malefic_Addons, 4)


PB_BIND(malefic_Addon, malefic_Addon, 2)


PB_BIND(malefic_LoadModule, malefic_LoadModule, 4)


PB_BIND(malefic_LoadAddon, malefic_LoadAddon, 4)


PB_BIND(malefic_ExecuteAddon, malefic_ExecuteAddon, 4)


PB_BIND(malefic_ExecuteBinary, malefic_ExecuteBinary, 4)


PB_BIND(malefic_ExecuteBinary_ParamEntry, malefic_ExecuteBinary_ParamEntry, AUTO)


PB_BIND(malefic_ExecuteCommand, malefic_ExecuteCommand, 2)


PB_BIND(malefic_UploadRequest, malefic_UploadRequest, 4)


PB_BIND(malefic_DownloadRequest, malefic_DownloadRequest, 2)


PB_BIND(malefic_DownloadResponse, malefic_DownloadResponse, 4)


PB_BIND(malefic_CurlRequest, malefic_CurlRequest, 4)


PB_BIND(malefic_CurlRequest_HeaderEntry, malefic_CurlRequest_HeaderEntry, AUTO)


PB_BIND(malefic_ChownRequest, malefic_ChownRequest, 2)


PB_BIND(malefic_IfconfigResponse, malefic_IfconfigResponse, 4)


PB_BIND(malefic_RegistryRequest, malefic_RegistryRequest, 2)


PB_BIND(malefic_Registry, malefic_Registry, 2)


PB_BIND(malefic_RegistryWriteRequest, malefic_RegistryWriteRequest, 4)


PB_BIND(malefic_TaskScheduleRequest, malefic_TaskScheduleRequest, 2)


PB_BIND(malefic_TaskSchedule, malefic_TaskSchedule, 2)


PB_BIND(malefic_TaskSchedulesResponse, malefic_TaskSchedulesResponse, 4)


PB_BIND(malefic_ServiceRequest, malefic_ServiceRequest, 2)


PB_BIND(malefic_ServiceConfig, malefic_ServiceConfig, 2)


PB_BIND(malefic_ServiceStatus, malefic_ServiceStatus, AUTO)


PB_BIND(malefic_Service, malefic_Service, 2)


PB_BIND(malefic_ServicesResponse, malefic_ServicesResponse, 4)


PB_BIND(malefic_WmiQueryRequest, malefic_WmiQueryRequest, 4)


PB_BIND(malefic_WmiMethodRequest, malefic_WmiMethodRequest, 2)


PB_BIND(malefic_WmiMethodRequest_ParamsEntry, malefic_WmiMethodRequest_ParamsEntry, AUTO)


PB_BIND(malefic_RunAsRequest, malefic_RunAsRequest, 2)


PB_BIND(malefic_GetSystem, malefic_GetSystem, 4)


PB_BIND(malefic_Inject, malefic_Inject, 4)


PB_BIND(malefic_Pipe, malefic_Pipe, 4)


PB_BIND(malefic_PipeRequest, malefic_PipeRequest, 4)


PB_BIND(malefic_Switch, malefic_Switch, 4)


PB_BIND(malefic_TaskCtrl, malefic_TaskCtrl, AUTO)


PB_BIND(malefic_TaskInfo, malefic_TaskInfo, AUTO)


PB_BIND(malefic_TaskListResponse, malefic_TaskListResponse, 2)


PB_BIND(malefic_FFmpegRequest, malefic_FFmpegRequest, 2)


PB_BIND(malefic_PtyRequest, malefic_PtyRequest, 4)


PB_BIND(malefic_PtyRequest_ParamsEntry, malefic_PtyRequest_ParamsEntry, AUTO)


PB_BIND(malefic_PtyResponse, malefic_PtyResponse, 4)


PB_BIND(malefic_PtyResponse_MetadataEntry, malefic_PtyResponse_MetadataEntry, AUTO)


PB_BIND(malefic_CommonBody, malefic_CommonBody, 4)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

