name: generate malefic

on:
  workflow_dispatch:
    inputs:
      remark:
        description: 'You can write something here, it will appear in the TITLE of `gh run list`, and help u find the artifact easily.'
        required: false
        default: ''
      release:
        description: 'Release version (default: none, if you want to upload to a GitHub Release, create a release and provide the version).'
        required: false
        default: "none"
      targets:
        description: 'Target to compile (comma separated, e.g., windows-x64-gnu,windows-x32-gnu)'
        required: true
      edition:
        description: 'Edition'
        required: false
        default: 'community'
      package:
        description: 'Package'
        required: true
        default: 'beacon'
      malefic_modules_features:
        description: 'Malefic modules features'
        required: false
        default: 'full'
      malefic_config_yaml:
        description: 'Malefic config (Base64-encoded content of config.yaml , will be masked in logs)'
        required: false
      autorun_yaml:
        description: 'Autorun config (Base64-encoded content of autorun.yaml , will be masked in logs)'
        required: false

run-name: ${{ github.event.inputs.remark }}

permissions:
  contents: write

jobs:
  set_targets:
    runs-on: ubuntu-22.04
    outputs:
      targets_json: ${{ steps.set_targets.outputs.targets_json }}
    steps:
      - name: Set matrix
        id: set_targets
        run: |
          TARGETS="${{ github.event.inputs.targets }}"
          TARGETS_JSON=$(echo "[\"${TARGETS//,/\",\"}\"]")
          echo "targets_json=$TARGETS_JSON" >> $GITHUB_OUTPUT

  generate:
    needs: set_targets
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: ${{ fromJson(needs.set_targets.outputs.targets_json) }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate config.yaml
        if : ${{ github.event.inputs.malefic_config_yaml != null }}
        run: |
          SECRET_CONFIG_YAML_CONTENT=$(jq -r '.inputs.malefic_config_yaml' $GITHUB_EVENT_PATH)
          echo "::add-mask::$SECRET_CONFIG_YAML_CONTENT"
          echo $SECRET_CONFIG_YAML_CONTENT
          echo "SECRET_CONFIG_YAML_CONTENT=$SECRET_CONFIG_YAML_CONTENT" >> $GITHUB_ENV
          echo "$SECRET_CONFIG_YAML_CONTENT" | base64 -d > config.yaml

      - name: Generate autorun.yaml
        if : ${{ github.event.inputs.autorun_yaml != null }}
        run: |
          SECRET_AUTORUN_YAML_CONTENT=$(jq -r '.inputs.autorun_yaml' $GITHUB_EVENT_PATH)
          echo "::add-mask::$SECRET_AUTORUN_YAML_CONTENT"
          echo "SECRET_AUTORUN_YAML_CONTENT=$SECRET_AUTORUN_YAML_CONTENT" >> $GITHUB_ENV
          echo "$SECRET_AUTORUN_YAML_CONTENT" | base64 -d > autorun.yaml

      - name: Build(${{ github.event.inputs.package }},${{matrix.target}})
        if : ${{ github.event.inputs.package != 'modules' }}
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
        run: |
          make target_triple=${{matrix.target}} ${{ github.event.inputs.package }}  -f ./Makefiles/Makefile.v0.0.3 

      - name: Build(${{ github.event.inputs.package }},${{matrix.target}})
        if : ${{ github.event.inputs.package == 'modules' }}
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
        run: |
          make target_triple=${{matrix.target}} ${{ github.event.inputs.package }} malefic_modules_features=${{ github.event.inputs.malefic_modules_features }} -f ./Makefiles/Makefile.v0.0.3  

      - name: Rename binary for ${{matrix.target}}
        run: |
          sudo chmod -R 777 target
          sudo chmod -R 777 output

      - name: Upload artifact ${{matrix.target}}
        if: ${{ github.event.inputs.release == 'none' }}
        uses: actions/upload-artifact@v4
        with:
          name: malefic-${{matrix.target}}-${{ github.run_id }}
          path: output/*
          retention-days: 3 # you can change this value

      - name: Release ${{ matrix.target }}
        if: ${{ github.event.inputs.release != 'none' }} # if you want to upload to a GitHub Release, create a release and provide the version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in output/*; do
            filename=$(basename "$file")
            if [[ "$filename" == "malefic.exe" || "$filename" == "malefic" ]]; then
              echo "Uploading $file"
              gh release upload ${{ github.event.inputs.release }} "$file"
            else
              echo "Skipping $file"
            fi
          done
        shell: bash
